apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-custom-config
  namespace: keycloak
data:
  custom-values.yaml: |
    auth: 
      adminUser: admin
      adminPassword: 
        valuesfrom: 
          secretKeyRef: 
            name: keycloak-secret
            key: admin-password
    extraEnv: 
      - name: KEYCLOAK_USER
        value: admin
      - name: KEYCLOAK_PASSWORD
        valueFrom: 
          secretKeyRef: 
            name: keycloak-secret
            key: admin-password
      - name: KC_PROXY
        value: edge
      - name: KC_HOSTNAME_STRICT
        value: "true"
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: "true"
    postgresql: 
      enabled: true
    tls: 
      enabled: true
    ingress: 
      enabled: true
      ingressClassName: nginx
      hostname: keycloak.alfredbrowniii.io
      rules:
        - host: keycloak.alfredbrowniii.io
          paths: 
            - path: / 
              pathType: Prefix

