apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-custom-config
  namespace: keycloak
data:
  custom-values.yaml: |
    auth: 
      adminUser: admin
      adminPassword: 
        valueFrom:    # Fixed the typo in 'valuesfrom'
          secretKeyRef: 
            name: keycloak-secret
            key: admin-password
    service: 
      ports: 
        https: 8443
        http: 8080    # Changed from 80 to 8080 to match Keycloak's default
    adminIngress: 
      enabled: true
      hostname: keycloak.alfredbrowniii.io
      annotations:    # Added necessary annotations for HTTPS backend
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    extraEnv: 
      - name: KEYCLOAK_USER
        value: admin
      - name: KC_HOSTNAME
        value: "keycloak.alfredbrowniii.io"
      - name: KEYCLOAK_PASSWORD
        valueFrom: 
          secretKeyRef: 
            name: keycloak-secret
            key: admin-password
      - name: KC_PROXY
        value: edge
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: "false"
    postgresql: 
      enabled: true
    tls: 
      enabled: true
      autoGenerated: true
    ingress: 
      enabled: true
      ingressClassName: nginx
      servicePort: https
      hostname: keycloak.alfredbrowniii.io
      annotations:    # Added necessary annotations for HTTPS backend
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/service-upstream: "true"
      rules:
        - host: keycloak.alfredbrowniii.io
          paths: 
            - path: / 
              pathType: Prefix