apiVersion: helm.toolkit.fluxcd.io/v2beta2 
kind: HelmRelease
metadata:
  name: devtron
  namespace: devtron
spec:
  patches: 
  - patch: | 
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
        namespace: devtron-cd
        labels:
          app.kubernetes.io/name: argocd-secret
          app.kubernetes.io/part-of: argocd
        annotations:
          "helm.sh/resource-policy": keep
    target: 
      kind: Secret 
      name: argocd-secret
      labelSelector: "app.kubernetes.io/name=argocd-secret"
  chart: 
    spec:
      chart: devtron-operator
      version: 0.22.78
      interval: 5h 
      sourceRef:
        kind: HelmRepository
        name: devtron
  interval: 1h 
  releaseName: devtron-operator
  valuesFrom: 
    - kind: ConfigMap 
      name: devtron
      valuesKey: custom-values.yaml

  