apiVersion: helm.toolkit.fluxcd.io/v2beta2 
kind: HelmRelease
metadata:
  name: devtron
  namespace: devtron
spec:
  patches: 
    - patch: | 
        - op: replace
          path: /metadata/namespace
          value: devtron-cd
  chart: 
    spec:
      chart: devtron-operator
      version: 0.22.78
      interval: 5h 
      sourceRef:
        kind: HelmRepository
        name: devtron
  interval: 1h 
  releaseName: devtron-operator
  valuesFrom: 
    - kind: ConfigMap 
      name: devtron
      valuesKey: custom-values.yaml

  