# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: rbac-controller
#   namespace: rbac-controller

---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbac-controller
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests", "certificatesigningrequests/approval", "certificatesigningrequests/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-controller
subjects:
- kind: ServiceAccount
  name: rbac-controller
  namespace: rbac-controller
roleRef:
  kind: ClusterRole
  name: rbac-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-controller
  namespace: rbac-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-controller
  template:
    metadata:
      labels:
        app: user-controller
    spec:
      serviceAccountName: user-controller
      containers:
      - name: controller
        image: aboogie/rbac-controller:latest  # Replace with your image
        env:
        - name: GIT_REPO_URL
          value: "https://your-git-repo-url"
        - name: GIT_REPO_PATH
          value: "/repo"
        - name: CERT_DIR
          value: "/certs"
        volumeMounts:
        - name: repo-volume
          mountPath: /repo
        - name: cert-volume
          mountPath: /certs
      volumes:
      - name: repo-volume
        emptyDir: {}
      - name: cert-volume
        emptyDir: {}