apiVersion: v1
kind: Service
metadata:
  name: glambychyna-service
  namespace: glambychyna
spec:
  type: ClusterIP
  selector:
    app: glambychyna
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80