apiVersion: helm.toolkit.fluxcd.io/v2beta2 
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: kubeapps
spec: 
  chart: 
    spec:
      chart: kubeapps
      version: 17.0.0
      interval: 5h 
      sourceRef:
        kind: HelmRepository
        name: kubeapps
  interval: 1h 
  releaseName: kubeapps

---

apiVersion: source.toolkit.fluxcd.io/v1beta2 
kind: HelmRepository
metadata:
  name: kubeapps
  namespace: kubeapps
spec: 
  url: oci://registry-1.docker.io/bitnamicharts/
  type: oci

---

apiVersion: v1 
kind: Namespace 
metadata: 
  name: kubeapps
  