apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy
  namespace: dashy
data:
  custom-values.yaml: |
    ingress: 
      enabled: true
      classname: nginx
      hosts: 
        - host: dashy.alfredbrowniii.io
          paths: 
            - path: /
              pathType: ImplementationSpecific
        
        