apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata: 
  name: k8s
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.4.196
  share: /mnt/pool1/k8s
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3
  - nolock
  - hard
  - intr
  - noatime 
  - nodiratime

