apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  releaseName: csi-driver-nfs
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.9.x
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  interval: 1h0m0s
  install:
    remediation:
      retries: 3