apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata: 
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.4.115
  share: /mnt/user/k8sContainers
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1  # NFSv4.1 is preferred for better performance
  - hard
  - noatime
  - nodiratime
  - rsize=1048576
  - wsize=1048576
  - timeo=600

