apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata: 
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.4.85
  share: /mnt/pve/k8sContainers
reclaimPolicy: Delete
volumeBindingMode: Immediate
