apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-nfs
  namespace: rook-nfs
spec:
  releaseName: rook-nfs
  chart:
    spec:
      chart: rook-nfs
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      version: "v1.10.3"  # Use the latest version available
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    operator:
      image:
        repository: rook/nfs
        tag: v1.10.3

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rook-release
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.rook.io/release
