apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor
  namespace: harbor
data:
  custom-values.yaml: |
    externalURL: https://harbor.alfredbrowniii.io
    expose: 
      type: ingress
      tls: 
        enabled: false
      ingress: 
        hosts: 
          core: harbor.alfredbrowniii.io
        className: nginx
    database:
      type: internal
      internal:
        extrInitContainers:
          - name: data-migrator
            image: goharbor/harbor-db:v2.4.1
            command: ["/bin/sh"]
            args:
              - '-c'
              - >-
                [ -e /var/lib/postgresql/data/postgresql.conf ] && [ ! -d
                /var/lib/postgresql/data/pgdata ] && chown -R postgres
                /var/lib/postgresql/data/ && mkdir -m 0700
                /var/lib/postgresql/data/pgdata && mv /var/lib/postgresql/data/*
                /var/lib/postgresql/data/pgdata/ || true
            resources: {}
            volumeMounts:
              - name: database-data
                mountPath: /var/lib/postgresql/data
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsUser: 0
          - name: data-permissions-ensurer2
            image: goharbor/harbor-db:v2.4.1
            command: ["/bin/sh"]
            args:
              - -c
              - mkdir -p /var/lib/postgresql/data/pgdata/pg15
              - chmod -R 700 /var/lib/postgresql/data/pgdata/pg15 || true
            volumeMounts:
              - name: database-data
                mountPath: /var/lib/postgresql/data
                subPath: null
          - name: data-ownership-ensurer
            image: goharbor/harbor-db:v2.4.1
            command: ["/bin/sh"]
            args:
              - -c
              - chown -R 999:999 /var/lib/postgresql/data || true
            volumeMounts:
              - name: database-data
                mountPath: /var/lib/postgresql/data
                subPath: null
        securityContext:
          fsGroup: 999
          runAsUser: 999
    redis: 
      master: 
        podSecurityContext: 
          fsGroup: 999
          runAsUser: 999
        containerSecurityContext:
          runAsUser: 999

        
        