apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor
  namespace: harbor
data:
  custom-values.yaml: |
    externalURL: https://harbor.alfredbrowniii.io
    exposureType: ingress
    ingress:
      core:
        ingressClassName: nginx
    
    # postgresql:
    #   primary:
    #     podSecurityContext: 
    #       fsGroup: 1001
    #       runAsUser: 1001
    #     containerSecurityContext:
    #       runAsUser: 1001
    # redis: 
    #   master: 
    #     podSecurityContext: 
    #       fsGroup: 1001
    #       runAsUser: 1001
    #     containerSecurityContext:
    #       runAsUser: 1001
        
        