apiVersion: helm.toolkit.fluxcd.io/v2beta2 
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec: 
  chart: 
    spec:
      chart: harbor
      version: 1.15.2
      interval: 5h 
      sourceRef:
        kind: HelmRepository
        name: harbor
  interval: 1h 
  releaseName: harbor
  valuesFrom: 
    - kind: ConfigMap 
      name: harbor
      valuesKey: custom-values.yaml

  