apiVersion: helm.toolkit.fluxcd.io/v2beta2 
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec: 
  chart: 
    spec:
      chart: harbor
      version: 1.4.x 
      interval: 5h 
      sourceRef:
        kind: HelmRepository
        name: harbor
  interval: 1h 
  releaseName: harbor
  