---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "12.x"  # Specify your desired version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Your values here - they can also be in a separate values.yaml
    image:
      debug: true
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      runAsUser: 1001
      runAsNonRoot: true

    # Container-level security context
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: false
      capabilities:
        drop: ["ALL"]

    # For init containers if needed
    volumePermissions:
      enabled: true
      securityContext:
        runAsUser: 0
    extraEnvVars: 
      - name: BITNAMI_DEBUG
        value: "true"
    global:
      postgresql:
        auth:
          postgresPassword: "yourpassword"
          username: "myuser"
          password: "mypassword"
          database: "mydatabase"
    persistence:
      size: 8Gi

