apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab
  namespace: gitlab
data:
  custom-values.yaml: |
    certmanager-issuer:
      email: alfred.brown@alfredbrowniii.io
    global:
      edition: ce
      hosts:
        https: false
        domain: alfredbrowniii.io
        externalIP: 10.0.4.247
      kas:
        enabled: false
      ingress: 
        configureCertmanager: false
    

        
        