# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: selfsigned-issuer
# spec:
#   selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ca2
  namespace: keycloak2
spec:
  isCA: true
  commonName: keycloak-ca2
  secretName: root-secret2
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keycloak-ca-issuer2
  namespace: keycloak2
spec:
  ca:
    secretName: root-secret2

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak2
  namespace: keycloak2
spec:
  secretName: keycloak-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - alfredbrowniii.io
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  commonName: keycloak2.alfredbrowniii.io
  dnsNames:
    - keycloak2.alfredbrowniii.io
  issuerRef:
    name: keycloak-ca-issuer2
    kind: Issuer