apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ca
  namespace: keycloak
spec:
  isCA: true
  commonName: keycloak-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keycloak-ca-issuer
  namespace: keycloak
spec:
  ca:
    secretName: root-secret

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: keycloak
spec:
  secretName: keycloak-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - alfredbrowniii.io
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  commonName: keycloak.alfredbrowniii.io
  dnsNames:
    - keycloak.alfredbrowniii.io
  issuerRef:
    name: keycloak-ca-issuer
    kind: Issuer